### ISSUE TITLE
Compilation error - missing namespace UI

### ISSUE THREAD

**Issue by tigerss** [Nobinator/Unity-UI-Rounded-Corners#2]
Hi,

I'm using Unity 2019.2.0b4 and this error comes up

`Assets\UiRoundedCorners\ImageWithRoundedCorners.cs(4,19): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)`

Any advice?

**Comment by Nobinator** [comment]
Hi tigerss,
This is mostly Editor or IDE problem. Try to reopen project and reimport all assets (right-click `Assets` Folder  -> `Reimport All`).

**Comment by tigerss** [comment]
I think the problem was from this file "Nobi.UiRoundedCorners.asmdef", I don't remember exactly how I solved it but not by reimporting
