### ISSUE TITLE
Unable to add transparency

### ISSUE THREAD

**Issue by maximus9600** [Nobinator/Unity-UI-Rounded-Corners#3]
After assigning the Image With Rounded Corners script to the panel , when I try to reduce the alpha of the Image componentto implement transparency , it seems to have no effect on the sprite. Is there a way to implement a panel with rounded corners and a transparent Image with this library?

**Comment by Nobinator** [comment]
Hi maximus9600!
I am going to update shaders for this soon (today or this week).

**Comment by maximus9600** [comment]
Thanks for replying @Nobinator
