### ISSUE TITLE
Add Color option

### ISSUE THREAD

**Issue by smxthereisonlyone** [Nobinator/Unity-UI-Rounded-Corners#5]
Hey,

I love your plugin! Would it be possible to add the possibility of coloring the texture as a shader setting?

I am using it on a quad and would like to be able to change the color when having a basic white rectangle texture as texture input.

Thanks a lot!

**Comment by Nobinator** [comment]
Hi @smxthereisonlyone!
Now there is a `UI/RoundedCorners/Manual` shader where you can place texture and color manually without Image component. Have a nice day :)

**Comment by Nobinator** [comment]
Feel free to reopen this issue if there is some problems with the shader
