### ISSUE TITLE
Center not filled on some mobile Devices

### ISSUE THREAD

**Issue by ZeBrody** [Nobinator/Unity-UI-Rounded-Corners#7]
On some mobile devices, the center is not filled (see screenshot)
Devices i encountered this issues are: HTC One_M8, Nexus 5
It works fine on other devices (Tested with Sony Xperia X Compact, Samsung S8, Oneplus 6)
![Screenshot_20191021-141111](https://user-images.githubusercontent.com/45146334/67204331-97338900-f40d-11e9-967e-b07f1218b48d.png)

I'm Using Unity 2019.2.9f1

**Comment by Nobinator** [comment]
I think there is a common origin of the problem with this and #4 issue. Thank you for the additional information. I am going to think about how to resolve this case. Would you able to help me by executing test shader that I will write soon (this weekend I hope)?

**Comment by ZeBrody** [comment]
Yes i'm glad to help.

**Comment by tomzorz** [comment]
Same issue here. Let me know if I can assist.

**Comment by iseta** [comment]
I'm getting the same issue here and so far it seems like something related to older android versions? I'll be running a few tests on this today and will report later.

**Comment by tomzorz** [comment]
Ah, to clarify: same issue here on PC / desktop / GTX1080 :)

**Comment by Nobinator** [comment]
The problem is probably solved, so, @suntabu will create a pull request, I hope :), and then you guys and check if it works properly

**Comment by iseta** [comment]
It seems to be working perfectly on all android versions I tested before. Will run a few final tests but honestly? I think that's it! 

Thank you @suntabu! 

He posted the code on issue #4 , and it adds a few lines to the roundedcorners.cginc file, I don't think he mentioned it on the specific issue but that's how I got it to work. Also, thank you @Nobinator for your plug-in, hope you have a nice vacation, man!

**Comment by suntabu** [comment]
> The problem is probably solved, so, @suntabu will create a pull request, I hope :), and then you guys will be able to check if it works properly

Sorry for late replying, and I saw you have already refactored all codes so I won't submit a PR for this.

Thanks again for your amazing plugin. :)
