### ISSUE TITLE
Radius resets to 0 on reload

### ISSUE THREAD

**Issue by Brettehwarrior** [Nobinator/Unity-UI-Rounded-Corners#9]
Pretty simply, when I relaunch a project some objects with the Rounded Corners script have their Radius value as well as the material's Z value reset to 0. I can recreate this every time I relaunch. 

GIF of what happens:

![uh oph](https://user-images.githubusercontent.com/17100539/71565331-01a71c00-2a84-11ea-9973-70a0cc119dd1.gif)

Each element was given its own material, and while in a session the radius works totally fine, it's just when relaunching the issue occurs. As seen the button object keeps its radius, making this even more confusing to me.

The only difference between the button and the other 2 elements that I can discern is that it isn't using a stretch anchor and the button a child of another element with rounded corners (not sure how either of those would have any effect though)

This is my first time messing around with Unity UI, and I was relieved to find such a simple solution to rounded corners, thank you so much for making this, hopefully I can get this figured out! I'm still learning Unity, so if there's additional information I should obviously be giving I apologize and I'm ready to provide more

**Comment by Brettehwarrior** [comment]
Still haven't figured out why this happens, but I moved the button object to elsewhere in the hierarchy and now it suffers from the issue as well. The fix I have now is a script on my UI Manager object which I called RoundedCornerUpdater:


```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[ExecuteInEditMode]
public class RoundedCornerUpdater : MonoBehaviour
{
    public float radius;

    void OnValidate() {
        foreach (var o in FindObjectsOfType<ImageWithRoundedCorners>()) {
            o.radius = radius;
        }
    }
}

```

Seems to work fine, but this isn't ideal for a project with objects that have differing radii

**Comment by Nobinator** [comment]
Hi @Brettehwarrior, thanks for your issue. 
There is only one place with force change of radius : ValidateConstraints.
```
private void ValidateConstraints(Rect rect){
    if (radius > rect.width) radius = rect.width;
    if (radius > rect.height) radius = rect.height;
    if (radius < 0) radius = 0;
}
```

It is called from `OnRectTransformDimensionsChange` and `OnValidate`. Seems like something went wrong while reloading and rect is turning to zero values for a frame that causes a radius reset.

This validation is optional and implemented not very well, so I just removed that.

Please checkout to branch `rm-constraints` and verify if everything works correctly for you. 
Thank you :)

**Comment by Brettehwarrior** [comment]
I commented out the ValidateConstraints() calls in the scripts and it seems to keep the shape fine now, thank you very much!
